const GAME_CONFIG = {
    // Stage and Combat
    CP_BASE: 1000,
    CP_MULTIPLIER: 499000,
    BOSS_HP_MULT: 120,
    NORMAL_HP_MULT: 20,
    BOSS_TIME_LIMIT: 60.0,
    
    // Weapon Upgrades
    WEAPON_EXPONENT: 1.45,
    ARMOR_EXPONENT: 1.45,
    SHIELD_EXPONENT: 1.45,
    SHOES_EXPONENT: 1.45,
    WEAPON_CLICK_MULT: 6,
    ARMOR_CLICK_MULT: 3,
    SHIELD_CLICK_MULT: 2,
    SHOES_CLICK_MULT: 2,
    
    WEAPON_DPS_MULT: 50,
    SHIELD_DPS_MULT: 40,
    SHOES_DPS_MULT: 30
};
